# Global seed
random_state: 42

# Verbose
verbose: True

# Some paths
example_set_local_path: 'data/ILLUIN/examples.csv'
clinc150_folder_local_path: 'data/CLINC150'

# Primary classes of interest
classes: ['translate',
          'travel_alert',
          'flight_status',
          'lost_luggage',
          'travel_suggestion',
          'carry_on',
          'book_hotel',
          'book_flight',
          'out_of_scope']

# Translator paths (huggingface)
translator_fr_en_model_path: 'Helsinki-NLP/opus-mt-tc-big-fr-en'
translator_en_fr_model_path: 'Helsinki-NLP/opus-mt-tc-big-en-fr'

# English model path (huggingface; pre-trained on CLINC150)
pretrained_english_model_path: "dbounds/roberta-large-finetuned-clinc"

# Encoder model paths (huggingface)
flaubert_model_path: 'flaubert/flaubert_base_uncased'
sentence_camembert_model_path: "dangvantuan/sentence-camembert-base"

# Recipes
recipes: {

  flaubert: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',  # see README.md for the list of oos strategies
                        'down',
                        'carry',
                        'trans'],
    training_inference_data_prep: ['stop',
                                    'flaubert',
                                    'avg'],
    add_val: True,
    model: "logReg"
  },

  camembert: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',
                          'down',
                          'carry',
                          'trans'],
    training_inference_data_prep: ['sentenceCamembert'],
    add_val: True,
    model: "logReg"
  }
}

# Best recipe
best_recipe: "camembert"