# Global seed
random_state: 42

# Verbose
verbose: True

# Some paths
example_set_local_path: 'data/ILLUIN/examples.csv'
clinc150_folder_local_path: 'data/CLINC150'

# Primary classes of interest
classes: ['translate',
          'travel_alert',
          'flight_status',
          'lost_luggage',
          'travel_suggestion',
          'carry_on',
          'book_hotel',
          'book_flight',
          'out_of_scope']

# Translator paths (huggingface)
translator_fr_en_model_path: 'Helsinki-NLP/opus-mt-tc-big-fr-en'
translator_en_fr_model_path: 'Helsinki-NLP/opus-mt-tc-big-en-fr'

# English model path (huggingface; pre-trained on CLINC150)
pretrained_english_model_path: "dbounds/roberta-large-finetuned-clinc"

# Encoder model paths (huggingface)
flaubert_model_paths: {
  falubertSmallCased: 'flaubert/flaubert_small_cased',
  flaubertBaseUncased: 'flaubert/flaubert_base_uncased',
  flaubertBaseCased: 'flaubert/flaubert_base_cased',
  flaubertLargeCased: 'flaubert/flaubert_large_cased'

}
sentence_camembert_model_paths: {
  sentenceCamembertBase: "dangvantuan/sentence-camembert-base",
  sentenceCamembertLarge: "dangvantuan/sentence-camembert-large"
}

# Propotion of OOS examples in the training set compared to the in-domain examples
proportion_oos: 2.5

# Recipes
recipes: {

  flaubert: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',  # see README.md for the list of oos strategies
                        'down',
                        'carry',
                        'trans'],
    training_inference_data_prep: ['stop',
                                    'flaubertBaseUncased',
                                    'avg'],
    add_val: True,
    model_type: "logReg"
  },

  flaubert_norm: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',  # see README.md for the list of oos strategies
                        'down',
                        'carry',
                        'trans'],
    training_inference_data_prep: ['stop',
                                    'flaubertBaseUncased',
                                    'avg',
                                    'norm'],
    add_val: True,
    model_type: "logReg"
  },

  flaubert_sum: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',  # see README.md for the list of oos strategies
                        'down',
                        'carry',
                        'trans'],
    training_inference_data_prep: ['stop',
                                    'flaubertBaseUncased',
                                    'sum'],
    add_val: True,
    model_type: "logReg"
  },

  flaubert_sum_norm: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',  # see README.md for the list of oos strategies
                        'down',
                        'carry',
                        'trans'],
    training_inference_data_prep: ['stop',
                                    'flaubertBaseUncased',
                                    'sum',
                                    'norm'],
    add_val: True,
    model_type: "logReg"
  },

  camembert: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',
                          'down',
                          'carry',
                          'trans'],
    training_inference_data_prep: ['sentenceCamembertBase'],
    add_val: True,
    model_type: "logReg"
  },

  camembert_noCarry: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',
                          'down',
                          'trans'],
    training_inference_data_prep: ['sentenceCamembertBase'],
    add_val: True,
    model_type: "logReg"
  },

  camembert_large: {
    clinc150_version: "plus",
    training_data_prep: ['oos1',
                          'down',
                          'carry',
                          'trans'],
    training_inference_data_prep: ['sentenceCamembertLarge'],
    add_val: True,
    model_type: "logReg"
  }
}

# Best recipe
best_recipe: "camembert"